development:
  adapter: postgresql
  encoding: unicode
  database: mt
  pool: 5
  username: mt
  password: 1234
  host: localhost
  port: 5432




production:
  adapter: postgresql
  encoding: unicode
  database: mt
  pool: 5
  username: mt
  password: 1234
  host: localhost
  port: 5432
